name: Build AppImage

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "10 0 * * *" # run at the start of every day after functions.py updates
  workflow_dispatch:

jobs:
  build-appimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip python3-setuptools curl rsync fuse libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev

      - name: Downloading misc dependencies
        run: |
          curl -L https://github.com/niess/python-appimage/releases/download/python3.10/python3.10.9-cp310-cp310-manylinux2014_x86_64.AppImage -o /tmp/python.AppImage
          curl -L https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -o /tmp/appimagetool.AppImage

      - name: Building AppImage
        run: bash .github/scripts/build-appimage.sh

      - name: Generating release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d_%H-%M")"

      - name: Creating new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: Automated AppImage build - ${{ steps.tag.outputs.release_tag }}
          body: |
            Prebuild AppImage of the eupnea initial setup, intended for use with Eupnea systems.
            [DO NOT RUN WITHOUT READING THE DISCLAIMER](https://github.com/eupnea-linux/eupnea-initial-setup#disclaimer)
          files: |
            /tmp/eupnea-initial-setup.AppImage